### ISSUE TITLE
(Design Team) - Download Page

### ISSUE THREAD

**Issue by vickst0rm** [zuri-training/Favicon-Gen-team62#116]
Design screens for the download pages after the favicons have been generated. Be sure to include preview pages.

**Comment by PeterXLs** [comment]
![Generate favicon - For download](https://user-images.githubusercontent.com/105240974/183522802-ddbef172-28a4-4e00-983d-8ebb8b4d608d.jpg)

Here attached is the image of the Download page as done with others

**Comment by Gbanama** [comment]
Task completed!

**Comment by Gbanama** [comment]
![sketch](https://user-images.githubusercontent.com/105219277/183870273-43260072-f5ef-4ccb-b8b7-7aeddde79e64.PNG)
