### ISSUE TITLE
(Design Team) - Saved Projects / Drafts

### ISSUE THREAD

**Issue by vickst0rm** [zuri-training/Favicon-Gen-team62#117]
Design a page where a user can find all the favicons that he / she has generated or saved so far

**Comment by Barakatonifade** [comment]
A page was designed where the user can find all favicons that have been generated so far

**Comment by Dandollars3** [comment]
The Saved Project page is designed to allow users have access to favicons that have been generated and also users are able to re-download or re-open the favicon for editing.
![Screenshot_20220809-094521_1](https://user-images.githubusercontent.com/105294705/183606846-243003aa-fa98-4e79-8de4-93d5040c9c1b.jpg)
