### ISSUE TITLE
(Design Team) - Mobile View Designs

### ISSUE THREAD

**Issue by vickst0rm** [zuri-training/Favicon-Gen-team62#120]
Design the screens for how the platform will look on mobile

**Comment by Caxri7** [comment]
Mobile views of the login page, signup page and forgot password pages

**Comment by Samuelafam** [comment]
Designed mobile views of the home page, generated page, home page signed in, contact us and image generated for download

**Comment by Faith-Jay** [comment]
Designed mobile view of the FAQ pages, Tutorial Pages and from gallery screen

**Comment by Dandollars3** [comment]
Designed Mobile Screen of About us, the Header of Mobile Screen, and Home page login
