### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by Karen-akuma** [zuri-training/Favicon-Gen-team62#13]

**Comment by Karen-akuma** [comment]
After researching with the team on the schema, i created the entities and attributes for our project 
[https://lucid.app/lucidchart/e2f6a74c-9ab1-4f51-8a11-9adfd9d47d5c/edit?viewport_loc=-132%2C-63%2C1480%2C649%2C0_0&invitationId=inv_2881c306-0bd0-4604-b1ed-9b517b3def1f#](url)

**Comment by Vidaz3** [comment]
I related the entities and made some adjustments to the attributes under each entity 
![IMG-20220730-WA0034](https://user-images.githubusercontent.com/105386682/182141902-d73643f9-3d50-4a7a-85ff-c9ab665d1fa1.jpg)
