### ISSUE TITLE
develop FAQs page

### ISSUE THREAD

**Issue by Karen-akuma** [zuri-training/Favicon-Gen-team62#135]

**Comment by Vidaz3** [comment]
Completed

**Comment by Vidaz3** [comment]
Will push the completed page later today.

**Comment by Vidaz3** [comment]
proof of my work..

![Screenshot (2)](https://user-images.githubusercontent.com/105386682/183996436-34598405-2a0b-4fbd-870b-ffe01ad57f3b.png)

![Screenshot (3)](https://user-images.githubusercontent.com/105386682/183996455-d2796a6e-54d1-4b0d-8336-286e01bca969.png)
