### ISSUE TITLE
develop Saved Projects page

### ISSUE THREAD

**Issue by Karen-akuma** [zuri-training/Favicon-Gen-team62#140]

**Comment by Vidaz3** [comment]
Done with this now.. Will push later in the day.

**Comment by Vidaz3** [comment]
proof of my work..

![Screenshot (2)](https://user-images.githubusercontent.com/105386682/183996225-5b125fc5-4ce7-4b7b-bfef-34ebd8088b40.png)
![Screenshot (3)](https://user-images.githubusercontent.com/105386682/183996283-6acbdba1-67d9-4220-b04a-5b0c5eb9ee01.png)
