### ISSUE TITLE
User research

### ISSUE THREAD

**Issue by Karen-akuma** [zuri-training/Favicon-Gen-team62#15]

**Comment by Gbanama** [comment]
The task has been completed👏

**Comment by Karen-akuma** [comment]
great, you can upload files or screenshots here. or give updates

**Comment by Faith-Jay** [comment]
Completed, attached are screenshots of the derived Empathy map and User persona.
<img width="620" alt="Empathy Map Favicon Gen" src="https://user-images.githubusercontent.com/105210181/182096544-dba52d46-2e15-446d-a1e6-86093755bf1d.png">
<img width="460" alt="User Persona Favicon gen" src="https://user-images.githubusercontent.com/105210181/182096598-388f78cf-05ca-4fd2-a160-4846b6362f4e.png">

**Comment by Gbanama** [comment]
Completed, attached below is a screenshot of the feature list agreed on by the team after the entire research process
![Featutre list, zuri](https://user-images.githubusercontent.com/105219277/182114273-cd0957a8-24c9-49dd-b184-ee0cd24f1b58.png)

**Comment by globutterbee** [comment]
Compleated task yea!

**Comment by globutterbee** [comment]
Completed task yea!
