### ISSUE TITLE
Research on SQL, mySQL e.tc and suggesting the best for the project

### ISSUE THREAD

**Issue by Karen-akuma** [zuri-training/Favicon-Gen-team62#26]

**Comment by Vidaz3** [comment]
I did some research comparing PostGreSQL, SQL server and mySQL. 
SQL server is mostly used by big companies who handle lots of data stream and its mostly a commercial tool. it has a free edition for individuals and small businesses which have limited memory and database sizes of 1gb and 10gb respectively,

mySQL  is very popular among big companies like amazon, google and linkedIn. its free edition gives access to base database functionalities but advanced tools can only be accessed by going premium.

PostgreSQL  is the most open source database. It offers various functionality options and it is absolutely free. I think it is the choice platform for our database system.

**Comment by VickoLee** [comment]
The most compatible database for a Django project is postgreSQL, Django's official documentation as well as their community also recommends postgreSQL for Django projects. For a vast majority of websites, PostgreSQL will work fine. It also has support for all data types .
You can read more about postgreSQL here: ⬇️
https://raturi.in/blog/best-database-for-django/

**Comment by EzenwakaAdachukwu** [comment]
I did a research comparing MYSQL and SQL and i discovered that SQL used to access and manipulate a database while MYSQL is a program that understands SQL but they are all on sever side.
