### ISSUE TITLE
Create Generate Favicon page (frame 147)

### ISSUE THREAD

**Issue by Karen-akuma** [zuri-training/Favicon-Gen-team62#3]

**Comment by XBigDeeX** [comment]
Alright chief. I'll begin tomorrow. I need to recover from preparing for and delivering the presentation.

**Comment by XBigDeeX** [comment]
Done Chief. Sent a pull request.

![image](https://user-images.githubusercontent.com/86341958/182136717-ea767327-76ed-47dc-95c8-93cda09bfbdd.png)
![Screenshot (50)](https://user-images.githubusercontent.com/86341958/182136743-c569a1f7-19b1-4c80-9335-49d2cdd0fb26.png)
![Screenshot (51)](https://user-images.githubusercontent.com/86341958/182136748-849d4c36-f978-4025-a149-367a27fc5a81.png)

**Comment by Karen-akuma** [comment]
merged to the main repository. weldone

**Comment by XBigDeeX** [comment]
Thanks Chief.
