### ISSUE TITLE
(Design Team) - User research

### ISSUE THREAD

**Issue by vickst0rm** [zuri-training/Favicon-Gen-team62#40]
Conduct an extensive research on the target user. Understand their pain points so that you can better design solutions that would meet their needs.

**Comment by Faith-Jay** [comment]
Completed

**Comment by vickst0rm** [comment]
This issue has been resolved. Supporting documents can be found in the Figjam work space **[HERE](https://www.figma.com/file/f4hAVA7P9u4s1u4Gb63Gy0/Team-62_Favicon-Gen?node-id=0%3A1)**

**Comment by Gbanama** [comment]
Task completed

**Comment by vickst0rm** [comment]
Contributed to the user research by reviewing interview and screener questions.

**Comment by Gbanama** [comment]
Contributed to the user research by creating a user research plan
conducting interviews
using interview results to find painpoints
and using the pain points we discovered to go through a whole lot of process and come up with a feature list

**Comment by Gbanama** [comment]
https://docs.google.com/document/d/1BOcxzQaBdfyRcYN6AgXN65DD6AnA1bblPIAKczIALqM/edit?usp=sharing

Here is the link to the research plan

**Comment by globutterbee** [comment]
conducted user research plan completed.   

 https://docs.google.com/document/d/1BOcxzQaBdfyRcYN6AgXN65DD6AnA1bblPIAKczIALqM/edit?usp=sharing
