### ISSUE TITLE
(Design Team) - Information architecture

### ISSUE THREAD

**Issue by vickst0rm** [zuri-training/Favicon-Gen-team62#41]
Create a simple Information Architecture for the project highlighting all major and sub links within the project.

**Comment by vickst0rm** [comment]
The information architecture of the platform which is the framework on which all visual designs are built has been created.
![Uploading Team 62_Favicon Gen.jpg…]()

**Comment by vickst0rm** [comment]
The information architecture of the platform which is the framework on which all visual designs are built has been created.
![Team 62_Favicon Gen](https://user-images.githubusercontent.com/72326114/183537260-994fca8c-16a9-41d0-8152-79809e336017.jpg)

**Comment by Barakatonifade** [comment]
The information architecture of the app was created

**Comment by Barakatonifade** [comment]
The information architecture for the app was created

**Comment by vickst0rm** [comment]
I reviewed the information architecture of the platform with my other colleagues.

**Comment by Dandollars3** [comment]
The information Architecture was properly constructed

**Comment by Lolueverywhere** [comment]
I made the Information Architecture with two other designers and it was reviewed by the Design Lead
