### ISSUE TITLE
(Design Team) - Style guide

### ISSUE THREAD

**Issue by vickst0rm** [zuri-training/Favicon-Gen-team62#42]
Create a comprehensive design system for use in the project.

**Comment by Samuelafam** [comment]
the comprehensive design system that included the input fields

**Comment by Caxri7** [comment]
The design system included different button variants and iconography packs.

**Comment by biteplug** [comment]
It also has input fileds for this projecr

**Comment by Barakatonifade** [comment]
Input fields were also included in the design

**Comment by tahwoh** [comment]
The design system included the 4px spacing, a guide for a uniform spacing for this project.

**Comment by Dandollars3** [comment]
The style guide had an icon pack which is being used during the design 
![Screenshot_20220804-043006](https://user-images.githubusercontent.com/105294705/183264638-6d99d33a-ebf3-4900-95a7-51b5dfaddd4e.jpg)

**Comment by PeterXLs** [comment]
The icon pack was sourced from Vuesax icons and can be downloaded from: https://freebiesbug.com/figma-freebies/iconsax/

**Comment by vickst0rm** [comment]
I worked on the colour styles, the grid, shadow, the typography as well as design elements that are under the miscellaneous items category. This included elements such as the footer, the navbar, the navigation items with variants (hover states).

**Comment by Lolueverywhere** [comment]
I worked on the Grid system
