### ISSUE TITLE
(Design Team) - Generate from image

### ISSUE THREAD

**Issue by vickst0rm** [zuri-training/Favicon-Gen-team62#46]
Design a page that would allow users that are registered and logged in to generate favicons from images that they upload

**Comment by vickst0rm** [comment]
![Image generate](https://user-images.githubusercontent.com/72326114/183539529-a2d183e6-ec7a-4728-aeb1-041cb892ce6d.jpg)

Proof of completion of this issue

**Comment by vickst0rm** [comment]
I designed and prototyped this page.

**Comment by Lolueverywhere** [comment]
I started the "Generate from Image" which was completed by another team member
