### ISSUE TITLE
(Design Team) - Login / Register / Forgot password

### ISSUE THREAD

**Issue by vickst0rm** [zuri-training/Favicon-Gen-team62#49]
Design the following pages for the platform taking into account the idle state, error state, active state and valid states for data entered

**Comment by Caxri7** [comment]
Login pages and forgot password with different states

**Comment by Faith-Jay** [comment]
Login and Register error states completed

**Comment by vickst0rm** [comment]
I prototyped every section of these pages that were designed by my colleagues.
