### ISSUE TITLE
(Design Team) - Empathy map

### ISSUE THREAD

**Issue by vickst0rm** [zuri-training/Favicon-Gen-team62#50]
Create an empathy map from research data gathered

**Comment by Faith-Jay** [comment]
<img width="565" alt="image" src="https://user-images.githubusercontent.com/105210181/183599562-6d1ff1e0-a60a-4fb5-86e5-8f29be6ed78e.png">

Completed

**Comment by Gbanama** [comment]
Task has been completed!
We created an empathy map from the research data gathered.

**Comment by globutterbee** [comment]
Empathy map assigned and completed.
