### ISSUE TITLE
Develop the Sign Up page (4 frames)

### ISSUE THREAD

**Issue by Karen-akuma** [zuri-training/Favicon-Gen-team62#52]

**Comment by XBigDeeX** [comment]
Completed and pushed already boss.

**Comment by XBigDeeX** [comment]
Proof of  m
![Screenshot (52)](https://user-images.githubusercontent.com/86341958/183994332-65c68a2c-cfef-4cb8-b236-860c8f54a37f.png)
y work
![Screenshot (55)](https://user-images.githubusercontent.com/86341958/183994371-cbae7c92-b4e2-4171-84fa-0b153560b43e.png)
.
