### ISSUE TITLE
(Design Team) - User persona

### ISSUE THREAD

**Issue by vickst0rm** [zuri-training/Favicon-Gen-team62#58]
Create a user persona that will help understand the target user better

**Comment by vickst0rm** [comment]
![Uploading Project Team 62 (Favicon_Gen)(3).png…]()

**Comment by vickst0rm** [comment]
<img width="1232" alt="Project Team 62 (Favicon_Gen)(3)" src="https://user-images.githubusercontent.com/72326114/183537476-15a42810-2c4f-46ab-97f3-67252135d47d.png">

**Comment by Faith-Jay** [comment]
Task Completed

**Comment by Gbanama** [comment]
Task has been completed

**Comment by globutterbee** [comment]
Complete task by me and other 2 designers.
