### ISSUE TITLE
(Design Team) - Home page

### ISSUE THREAD

**Issue by vickst0rm** [zuri-training/Favicon-Gen-team62#63]
Design a minimal yet aesthetic home page for the favitude platform.

**Comment by biteplug** [comment]
Kindly check to see what we did as well as corrections assigned.

**Comment by Zitabenita** [comment]
Done already👍🏾

**Comment by Samuelafam** [comment]
![Screenshot (60)](https://user-images.githubusercontent.com/105444864/183591759-2255eeed-a476-46bd-a356-837fda1ba7b6.png)

**Comment by Gbanama** [comment]
Task completed👍

**Comment by vickst0rm** [comment]
I prototyped the homepage in its entirety.

**Comment by Gbanama** [comment]
![Homepage](https://user-images.githubusercontent.com/105219277/183874262-c9f08dae-7808-44b0-a50b-87517e2160ff.PNG)
