### ISSUE TITLE
(Design Team) - Download page for Text / Image / Gallery

### ISSUE THREAD

**Issue by vickst0rm** [zuri-training/Favicon-Gen-team62#66]
Your tasks borders around designing a page that users will be taken to in order to download or save the favicons that they have generated using the platform

**Comment by PeterXLs** [comment]
Page completed. Please see attache
![Generate favicon - For download](https://user-images.githubusercontent.com/105240974/183466594-c1351b18-0c18-49e0-921d-d3c8e8a9a8a1.jpg)
d

**Comment by Gbanama** [comment]
This is how we designed the download page:
first we drew a sketch,
we made sure to include features that enables the user to perform specific actions on that page,
like: preview favicon, save as draft, download favicon in different formats, see previous downloads.
attached below is the image of the original sketch.

**Comment by Gbanama** [comment]
![sketch](https://user-images.githubusercontent.com/105219277/183871427-f8aa91fa-c7bf-4e29-b715-4923ab3a738f.PNG)
